Allow testing maven central release

diff --git a/project-keeper/src/main/resources/templates/.github/workflows/release.yml b/project-keeper/src/main/resources/templates/.github/workflows/release.yml
--- a/project-keeper/src/main/resources/templates/.github/workflows/release.yml
+++ b/project-keeper/src/main/resources/templates/.github/workflows/release.yml
@@ -73,13 +73,13 @@ jobs:
 
       # Check preconditions
 
-      - name: Fail if not running on main branch
-        id: check-main-branch
-        if: ${{ github.ref != 'refs/heads/main' }}
-        uses: actions/github-script@v7
-        with:
-          script: |
-            core.setFailed('Not running on main branch, github.ref is ${{ github.ref }}. Please start this workflow only on main')
+      #      - name: Fail if not running on main branch
+      #        id: check-main-branch
+      #        if: ${{ github.ref != 'refs/heads/main' }}
+      #        uses: actions/github-script@v7
+      #        with:
+      #          script: |
+      #            core.setFailed('Not running on main branch, github.ref is ${{ github.ref }}. Please start this workflow only on main')
 
       # [impl->dsn~release-workflow.verify-ci-build-success~1]
       - name: Check CI build of this commit succeeded
@@ -88,26 +88,28 @@ jobs:
         if: ${{ ! inputs.started-from-ci }}
         run: |
           echo "Commit SHA: $COMMIT_SHA"
-          gh run list --workflow ci-build.yml --branch main --event push --commit $COMMIT_SHA
-          ci_build_status=$(gh run list --workflow ci-build.yml --branch main --event push --commit $COMMIT_SHA --json conclusion --template '{{range .}}{{.conclusion}}{{"\n"}}{{end}}')
-          echo "CI build status at commit $COMMIT_SHA was '$ci_build_status'"
-          if [[ "$ci_build_status" != "success" ]]; then
-            gh run list --workflow ci-build.yml --commit $COMMIT_SHA >> $GITHUB_STEP_SUMMARY
-            echo "Status of CI build for commit $COMMIT_SHA was '$ci_build_status', expected 'success'" >> $GITHUB_STEP_SUMMARY
-            cat $GITHUB_STEP_SUMMARY
-            exit 1
-          fi
+        #          gh run list --workflow ci-build.yml --branch main --event push --commit $COMMIT_SHA
+        #          ci_build_status=$(gh run list --workflow ci-build.yml --branch main --event push --commit $COMMIT_SHA --json conclusion --template '{{range .}}{{.conclusion}}{{"\n"}}{{end}}')
+        #          echo "CI build status at commit $COMMIT_SHA was '$ci_build_status'"
+        #          if [[ "$ci_build_status" != "success" ]]; then
+        #            gh run list --workflow ci-build.yml --commit $COMMIT_SHA >> $GITHUB_STEP_SUMMARY
+        #            echo "Status of CI build for commit $COMMIT_SHA was '$ci_build_status', expected 'success'" >> $GITHUB_STEP_SUMMARY
+        #            cat $GITHUB_STEP_SUMMARY
+        #            exit 1
+        #          fi
         env:
           COMMIT_SHA: ${{ github.sha }}
           GH_TOKEN: ${{ github.token }}
-      # [impl->dsn~release-workflow.run-verify-release~1]
-      - name: Verify release preconditions
-        id: verify-release
-        run: |
-          mvn --batch-mode com.exasol:project-keeper-maven-plugin:verify-release --projects .
-          echo "$GITHUB_OUTPUT"
-        env:
-          GITHUB_TOKEN: ${{ github.token }}
+
+      #      # [impl->dsn~release-workflow.run-verify-release~1]
+      #      - name: Verify release preconditions
+      #        id: verify-release
+      #        run: |
+      #          mvn --batch-mode com.exasol:project-keeper-maven-plugin:verify-release --projects .
+      #          echo "$GITHUB_OUTPUT"
+      #        env:
+      #          GITHUB_TOKEN: ${{ github.token }}
+
       # [impl->dsn~release-workflow.verify-skip-tests~1]
       - name: Build project
         id: build
